# -*- coding: utf-8 -*-
"""Bokeh Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zGTnN1MJJ0GZ3PLeHWVj5_oVkW74uIwi
"""

#Q1
from bokeh.plotting import figure, show
from bokeh.io import output_notebook

# Enable output in the notebook (if using Jupyter)
output_notebook()

# Create a figure object
p = figure(title="Simple Line Plot", x_axis_label="X-Axis", y_axis_label="Y-Axis")

# Add a line renderer with a legend and line thickness
p.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], legend_label="Temp.", line_width=2)

# Show the plot
show(p)

#Q2
"""Glyphs are the basic visual building blocks in Bokeh. They represent shapes or markers such as circles, squares, lines, rectangles, etc., that can be used to display data points on a plot."""

#Q3
from bokeh.plotting import figure, show
from bokeh.io import output_notebook

# Enable output in the notebook
output_notebook()

# Create a figure object
p = figure(title="Customized Bokeh Plot", x_axis_label="X-Axis", y_axis_label="Y-Axis")

# Customize title
p.title.text_font_size = "20pt"
p.title.align = "center"
p.title.text_color = "green"

# Customize axes
p.xaxis.axis_label_text_color = "blue"
p.xaxis.axis_label_text_font_size = "14pt"
p.yaxis.axis_label_text_color = "red"
p.yaxis.axis_label_text_font_size = "14pt"

# Customize legend
p.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], legend_label="Line", line_width=2, color="orange")
p.legend.title = "Legend"
p.legend.title_text_font_size = "12pt"
p.legend.label_text_font_size = "10pt"
p.legend.location = "top_left"

# Show the plot
show(p)

#Q4
"""Bokeh server allows you to create interactive plots that can be updated in real time based on user interactions or other events. It provides a way to build web applications that can dynamically update plots without requiring a full page reload."""

#Q5
"""You can embed a Bokeh plot into a web application using Flask or Django by rendering the plot components (JavaScript and HTML) within your web page."""