# -*- coding: utf-8 -*-
"""Plotly Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11R1C2WfbHFIJUglm2Z9QbXxfdl6-XhRc
"""

#Q1
import seaborn as sns
import plotly.express as px

# Load the Titanic dataset using Seaborn
titanic = sns.load_dataset('titanic')

# Create a scatter plot using Plotly Express
fig1 = px.scatter(titanic, x='age', y='fare', title='Scatter Plot of Age vs Fare in Titanic Dataset')
fig1.show()

#Q2
import plotly.express as px

# Load the tips dataset using Plotly Express
tips = px.data.tips()

# Create a box plot using Plotly Express
fig2 = px.box(tips, x='day', y='total_bill', title='Box Plot of Total Bill by Day')
fig2.show()

#Q3
import plotly.express as px

# Load the tips dataset using Plotly Express
tips = px.data.tips()

# Create a histogram using Plotly Express
fig3 = px.histogram(tips, x="sex", y="total_bill", color="day", pattern_shape="smoker", title='Histogram of Total Bill by Sex with Day and Smoker Pattern')
fig3.show()

#Q4
import plotly.express as px

# Load the iris dataset using Plotly Express
iris = px.data.iris()

# Create a scatter matrix plot using Plotly Express
fig4 = px.scatter_matrix(iris, dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"], color="species", title='Scatter Matrix of Iris Dataset')
fig4.show()

#Q5
import plotly.figure_factory as ff

# Create a distribution plot using Plotly Express (Distplot)
data = [titanic['age'].dropna()]  # Use age column from the Titanic dataset for demonstration
group_labels = ['Age Distribution']

# Create distplot
fig5 = ff.create_distplot(data, group_labels, show_hist=True, show_rug=False)
fig5.update_layout(title='Distplot of Age Distribution in Titanic Dataset')
fig5.show()

